# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: travel-umrah
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: travel-umrah
#   template:
#     metadata:
#       labels:
#         app: travel-umrah
#     spec:
#       containers:
#       - name: travel-umrah
#         image: docker.io/fandymora02/travel-umrah-web:latest
#         ports:
#         - containerPort: 3000
#         resources:
#           requests:
#             cpu: "100m"
#             memory: "128Mi"
#           limits:
#             cpu: "500m"
#             memory: "256Mi"


apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-umrah
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-umrah
  template:
    metadata:
      labels:
        app: travel-umrah
    spec:
      containers:
        - name: travel-umrah
          image: travel-umrah:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
