# apiVersion: v1
# kind: Service
# metadata:
#   name: travel-umrah
# spec:
#   selector:
#     app: travel-umrah
#   ports:
#   - port: 80
#     targetPort: 3000
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: travel-umrah
spec:
  type: NodePort
  selector:
    app: travel-umrah
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
