name: CI/CD Kubernetes - Travel Umrah

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USER }}/travel-umrah:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USER }}/travel-umrah:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl rollout restart deployment travel-umrah

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | podman login docker.io -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image to DockerHub
        run: podman tag travel-umrah-web docker.io/${{ secrets.DOCKER_USER }}/travel-umrah-web:latest

      - name: Push
        run: podman push docker.io/${{ secrets.DOCKER_USER }}/travel-umrah-web:latest

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment travel-umrah

